### ISSUE TITLE
Applicaton startup 

### ISSUE THREAD

**Issue by Ashish-Soni08** [lablab-ai/Google-VertexAI-FastAPI#1]
Hi @mkbctrl  I tried running the app but ran into issues.. 

## What I did 
- changed the `project_id` in `service_account.json` provided by lablabai to my `project_id` and also changed the location in `main.py`
- and had to change the port to 8081 

![app_fastapi](https://github.com/lablab-ai/Google-VertexAI-FastAPI/assets/44482363/e0981955-528a-40cb-8f44-404f6b3a38ec)

## What else do I need to change/do?

**Comment by mkbctrl** [comment]
the entire service account key you received or created should go into the `service_account.json` file. You can't change the id, cause it's a part of the entire key, the key is binded to the rest of the properties you have in the file.
